/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  safelist: [
    "bg-banner-tolima",
    "bg-banner-narino",
    "bg-banner-santander",
    "bg-banner-boyaca",
    "bg-banner-colombia",
    "bg-banner-acerca-de",
    "bg-banner-glosario",
    "bg-banner-metodologia",
    "bg-banner-preguntas-frecuentes",
    "bg-banner-prensa",
    "bg-banner-publicadores",
    "bg-banner-regiones",
    "bg-banner-mas",
    "bg-prensa",
    "bg-footer-orange",
    "bg-footer-green",
  ],
  theme: {
    extend: {
      height: {
        "screen-75": "75vh",
      },
      fontFamily: {
        "barlow-condensed": ["'Barlow Condensed'", "sans-serif"],
        lato: ["Lato", "sans-serif"],
        inter: ["Inter", "sans-serif"],
      },
      backgroundImage: {
        prensa: "url('/images/banner-prensa.svg')",
        "banner-home": "url('/images/headers/banner-home-3.jpg')",
        "banner-mas": "url('/images/headers/banner-mas.png')",
        "banner-boyaca": "url('/images/banner-principales/boyaca.jpg')",
        "banner-narino": "url('/images/banner-principales/narino.jpg')",
        "banner-santander": "url('/images/banner-principales/santander.jpg')",
        "banner-tolima": "url('/images/banner-principales/tolima.jpg')",
        "banner-colombia": "url('/images/banner-principales/colombia.jpg')",
        "banner-regiones": "url('/images/banner-principales/regiones.jpg')",
        "banner-acerca-de": "url('/images/banner-principales/mas-acerca-de.jpg')",
        "banner-glosario": "url('/images/banner-principales/mas-glosario.jpg')",
        "banner-metodologia": "url('/images/banner-principales/mas-metodologia.jpg')",
        "banner-preguntas-frecuentes": "url('/images/banner-principales/mas-preguntas-frecuentes.jpg')",
        "banner-prensa": "url('/images/banner-principales/mas-prensa.jpg')",
        "banner-publicadores": "url('/images/banner-principales/mas-publicadores.jpg')",
        "footer-orange": "url('/images/footers/orange-footer.svg')",
        "footer-green": "url('/images/footers/green-footer.svg')",
      },
      backgroundPosition: {
        "center-bottom": "center bottom",
      },
      colors: {
        "white-2": "#FBFBFB",
        "white-3": "#F1F1F1",
        "white-smoke": "#F5F5F5",
        "gray-2": "#F4F4F4",
        "blue-green": "#005054",
        "black-2": "#000000CC",
        "black-3": "#00000066",
        lemon: "#09A274",
        "yellow-green": "#C2F284",
        "dartmouth-green": "#00634B",
        cerulean: "#00AFFF",
        azure: "#0090FF",
        "catalina-blue": "#001975",
        "science-blue": "#0857C9",
        sandstorm: "#FFD150",
        "greenish-cyan": "#4AD3AC",
        "red-cr": "#ff0000",
        "orange-en": "#ffa500",
        burnham: "#002B2C",
        "yellow-orange": "#FFB349",
        "yellow-vu": "#ffff00",
        flame: "#E1501B",
        "light-peagreen": "#C7F789",
        "dark-periwinkle": "#6363DC",
        "pastel-periwinkle": "#8FABFF",
        blueberry: "#4B3CB4",
        "pastel-orange": "#FF9739",
        "light-orange": "#FFBC4E",
        "peach-crayola": "#FFCC99",
        "cornflower-blue": "#6699FF",
        "navajo-white": "#FFDFAB",
        "majorelle-blue": "#5151F2",
        "giants-orange": "#F26330",
        platinum: "#D9D9D9",
      },
      boxShadow: {
        default: "0px 3px 6px #00000029",
        select: "0px 11px 11px #0000001F",
        hard: "0px 8px 8px #00000017",
      },
      screens: {
        "3xl": "1920px",
      },
      keyframes: {
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(-4px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "fade-in": "fade-in 180ms ease-out",
      },
    },
  },
  plugins: [],
};
